# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://distracted-cray-6367b4.netlify.com'
baseurl: ''
title: 'Jekyll'
description: 'Jekyll Test Site'
permalink: pretty
logo: ""

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
#- title: Hosting
#  url: /hosting/
#- title: Development
#  url: /development/  
#- title: Domains
#  url: /domains/
#- title: Member Login
#  url: /login/  
#- title: About
#  url: /about/ 
#- title: Tools
#  url: /about/      

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Developer Blog"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
